'use client';
import '@repo/ui/styles.css';
import './globals.css';
import './index.css';
import { Geist } from 'next/font/google';
import { ConvexAuthProvider } from '@convex-dev/auth/react';
import { ConvexReactClient } from 'convex/react';
import { Toaster } from 'sonner';

const geist = Geist({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Turborepo',
//   description: 'Generated by create turbo',
// };

const convex = new ConvexReactClient(process.env.NEXT_PUBLIC_CONVEX_URL!);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={geist.className}>
        <ConvexAuthProvider client={convex}>
          <Toaster position='top-center' />
          {children}
        </ConvexAuthProvider>
      </body>
    </html>
  );
}
